# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('twitter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_id', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_name', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tweet_count', models.IntegerField(default=0)),
                ('insta_count', models.IntegerField(default=0)),
                ('posts', models.ManyToManyField(to='twitter_insta.Post')),
            ],
        ),
    ]
